version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    open-pull-requests-limit: 10
    directories:
      - '**/*'
    schedule:
      interval: 'monthly'
    groups:
      electron:
        patterns:
          - 'electron'
          - 'electron-*'
          - '@electron-toolkit/*'
      vue:
        patterns:
          - 'vue'
          - '@vue/*'
          - 'pinia'
          - '@vitejs/plugin-vue'
          - 'vue-tsc'
          - 'vue-eslint-parser'
          - 'eslint-plugin-vue'
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@typescript-eslint/*'
        exclude-patterns:
          - 'eslint-plugin-vue'
      typescript:
        patterns:
          - 'typescript'
          - '@types/*'
      prettier:
        patterns:
          - 'prettier'
          - '@prettier/*'
      vite:
        patterns:
          - 'vite'
          - 'electron-vite'
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
