# These are supported funding model platforms

patreon: Netroforge # Replace with a single Patreon username
open_collective: netroforge # Replace with a single Open Collective username
ko_fi: netroforge # Replace with a single Ko-fi username
