# These are supported funding model platforms

github: [Hronom] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Netroforge # Replace with a single Patreon username
open_collective: netroforge # Replace with a single Open Collective username
ko_fi: netroforge # Replace with a single Ko-fi username
