name: Electron Builder Linux

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sudo apt-get update && sudo apt-get install -y rpm
          sudo snap install snapcraft --classic
          npm install
          #To generate SNAP_TOKEN run `snapcraft export-login [FILE]` and login with your snapcraft credentials. It is used now without login
          npm run publish:linux
