name: Electron Builder CI (MAC)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Build
        run: |
          npm build:mac
