name: Generate sha256 hashes for release files

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Hashes
        uses: MCJack123/ghaction-generate-release-hashes@v4
        with:
          hash-type: sha256
          file-name: hashes.txt
      - name: Debug
        run: |
          ls
      - name: Upload Hashes to release
        uses: actions/upload-artifact@v4
        with:
          name: Asset Hashes
          path: hashes.txt
